CONTRIBUTORS.md
=> [doc] Update contributors.md

Hack/Backend/controllers/LocationController.js, Hack/Backend/db.js, Hack/Backend/index.js, Hack/Backend/models/LocationModel.js, Hack/Backend/package-lock.json, Hack/Backend/package.json, Hack/Backend/routes/LocationRoutes.js
Location Model with CRUD implementation
=> Added Location Models

Hack/Backend/controllers/LocationUserController.js, Hack/Backend/models/LocationUserModel.js, Hack/Backend/models/location_user_test.js, Hack/Backend/routes/LocationUserRoutes.js
Implement Controller
[db] Implement rounter for location_user
[db] update test explanation
=> [db] Add location_user with test

Hack/Backend/controllers/SymptomController.js, Hack/Backend/controllers/SymptomUserController.js, Hack/Backend/index.js, Hack/Backend/models/Symptom.js, Hack/Backend/models/SymptomUser.js, Hack/Backend/routes/SymptomRoutes.js, Hack/Backend/routes/SymptomUserRoutes.js
Create controller and routes for Symptom and SymptomUser models
=> [db] add symptom controller and symptomuser controller

Hack/Backend/package-lock.json, Hack/Backend/package.json
=> [db] add symptom controller and symptomuser controller updated package.json

Hack/Backend/controllers/SymptomController.js
temporarily removed joi validation
=> Anteneh.controllerupdates

Hack/Backend/controllers/LocationController.js, Hack/Backend/controllers/LocationUserController.js, Hack/Backend/controllers/SymptomController.js, Hack/Backend/controllers/SymptomUserController.js, Hack/Backend/controllers/UserController.js, Hack/Backend/middlewares/auth.js, Hack/Backend/models/SymptomUser.js, Hack/Backend/package-lock.json, Hack/Backend/package.json, Hack/Backend/routes/LocationRoutes.js, Hack/Backend/routes/LocationUserRoutes.js, Hack/Backend/routes/SymptomRoutes.js, Hack/Backend/routes/SymptomUserRoutes.js, Hack/Backend/routes/UserRoutes.js
End point authentication implemented
=> Mohammed.api implementation

Hack/Backend/controllers/LocationController.js, Hack/Backend/controllers/LocationUserController.js, Hack/Backend/models/LocationModel.js, Hack/Backend/models/LocationUserModel.js, Hack/Backend/routes/LocationRoutes.js, Hack/Backend/routes/SymptomUserRoutes.js
The risk assessment for one particular location at that
time is provided by adding up the symptom risk levels for
each instance of a symptom.
[db] Add place name to location
[db] Make location user IDs unique in locationuser
[fix] minor bug
[api] Add route for risk factor
=> [api] Implement place risk factor assessment

Hack/Backend/controllers/LocationController.js, Hack/Backend/routes/LocationRoutes.js, Hack/Backend/routes/SymptomRoutes.js, Hack/Backend/routes/SymptomUserRoutes.js
Added End point needed for mapping
=> [api] Added Location User With Symptom Checker Endpoint

Hack/Backend/controllers/LocationController.js, Hack/Backend/controllers/LocationUserController.js, Hack/Backend/controllers/SymptomController.js, Hack/Backend/routes/LocationRoutes.js, Hack/Backend/routes/LocationUserRoutes.js, Hack/Backend/routes/SymptomRoutes.js, Hack/Backend/routes/SymptomUserRoutes.js
[integration] fixed a bug in symptom and a few routes
=> Khalid.integration

Hack/Backend/controllers/LocalPolicyController.js, Hack/Backend/models/LocalPolicyModel.js, Hack/Backend/routes/LocalPolicyRoutes.js
[api] implement localpolicy api
[api] add route for local polices
[fix] various fixes
=> [db] implement localPolicy

Hack/Backend/controllers/AlertController.js, Hack/Backend/controllers/AlertUserController.js, Hack/Backend/controllers/NewsController.js, Hack/Backend/models/AlertModel.js, Hack/Backend/models/AlertUserModel.js, Hack/Backend/models/UserModel.js, Hack/Backend/package-lock.json, Hack/Backend/package.json, Hack/Backend/routes/AlertRoutes.js, Hack/Backend/routes/AlertUserRoutes.js
[db] Added Alert Model
[api] News Fetching from external sources
=> [db] Added Alert Model and News Fetching

Hack/Backend/db.js, Hack/Backend/index.js, Hack/Backend/package.json
Enable env variables for MONGODB_URI and PORT
Add start script
=> [backend] Setup Project for deployment on heroku

Hack/Backend/controllers/MedicalHistoryController.js, Hack/Backend/controllers/MedicalHistoryUserController.js, Hack/Backend/controllers/SymptomController.js, Hack/Backend/index.js, Hack/Backend/index.js.orig, Hack/Backend/models/MedicalHistory.js, Hack/Backend/models/MedicalHistoryUser.js, Hack/Backend/models/SymptomUser.js, Hack/Backend/routes/MedicalHistoryRoutes.js, Hack/Backend/routes/MedicalHistoryUserRoutes.js
Added the MedicalHistory and MedicalHistoryUser models along with their controllers
=> Anteneh.new datamodel implementation

covid-19-app-web/src/App.vue, covid-19-app-web/src/components/core/AppFooter.vue, covid-19-app-web/src/views/About/About.vue
Contains Description section, Actions section, and Contact us Section
=> [frontend] Build initial About Page

Hack/Backend/controllers/StatisticsController.js, Hack/Backend/routes/StatisticsRoutes.js
[api] Create filter and routes
[fix] Run updates at file load
[db] Add some comments
=> [api] add statistics implementation

Hack/Backend/controllers/StatisticsController.js, Hack/Backend/controllers/assets/ReadMe.md
[config] add asset folder and description
=> [fix] fetch updates daily

Hack/Backend/controllers/NewsController.js, Hack/Backend/routes/NewsRoutes.js
The CDC link is the only one that i found feasible. The others either don't have a description or have news of other languages.
=> Lydia.fetch more news

COVID19_Mobile_Application/components/public-data-page/DataAnalytics.js, COVID19_Mobile_Application/package-lock.json, COVID19_Mobile_Application/package.json
[mobile] public data statics page search design implemented
[mobile] public data statics page data preview cards added
[mobile] public data statics page graph with mock data implemented
[mobile] public data statics page graph data filtering implemnted
[mobile] publid data static page completed
=> [mobile] public data static page basic start

Hack/Backend/controllers/UserController.js, Hack/Backend/models/UserModel.js, Hack/Backend/routes/UserRoutes.js
updating the age ranges(not date) and updating the age of users
=> [db] updating the date ranges

Hack/Backend/config/development.json, Hack/Backend/config/production.json, Hack/Backend/controllers/LocationController.js, Hack/Backend/controllers/LocationUserController.js, Hack/Backend/controllers/LogController.js, Hack/Backend/controllers/SymptomController.js, Hack/Backend/controllers/SymptomUserController.js, Hack/Backend/controllers/UserController.js, Hack/Backend/middlewares/auth.js, Hack/Backend/package-lock.json, Hack/Backend/package.json, Hack/Backend/routes/AlertRoutes.js, Hack/Backend/routes/AlertUserRoutes.js, Hack/Backend/routes/LocationRoutes.js, Hack/Backend/routes/LocationUserRoutes.js, Hack/Backend/routes/LogRoutes.js, Hack/Backend/routes/MedicalHistoryRoutes.js, Hack/Backend/routes/MedicalHistoryUserRoutes.js, Hack/Backend/routes/MessageRoutes.js, Hack/Backend/routes/SymptomRoutes.js, Hack/Backend/routes/SymptomUserRoutes.js, Hack/Backend/routes/UserRoutes.js
adding jwt verification for all routes
=> [security] adding authorization for every route

Hack/Backend/controllers/LocationController.js, Hack/Backend/controllers/MapDataController.js, Hack/Backend/models/LocationUserModel.js, Hack/Backend/models/SymptomUser.js
Tried to optimize the locations_symptoms endpoint due to the high influx of users data inserted
=> [api] Attempt to fix Locations Symptoms Endpoint

Hack/Backend/controllers/LocationController.js, Hack/Backend/controllers/LocationUserController.js, Hack/Backend/middlewares/auth.js, Hack/Backend/models/LocationModel.js, Hack/Backend/routes/LocationRoutes.js, Hack/Backend/services/ProbabilityCalculator.js, Hack/Backend/test/LocationControllerTest.js, Hack/Backend/test/LocationUserControllerTest.js
Code Reviews for Location and LocationUser. [Includes Routes, Models, Controllers and Tests]
=> Khalid.code reviews

Hack/Backend/controllers/LocationUserController.js, Hack/Backend/controllers/LogController.js
Added Backing up of Log data hourly function
Modified update frequency of location grid
=> [api] Backing up logs and bug fix

covid-19-app-web/src/components/core/AppBar.vue, covid-19-app-web/src/store/loaders.js, covid-19-app-web/src/store/symptom-tracking.js, covid-19-app-web/src/views/Auth/Login.vue, covid-19-app-web/src/views/HeatMap/HeatMap.vue, covid-19-app-web/src/views/HeatMap/Maps/SymTrack.vue, covid-19-app-web/src/views/Home/Ethiopia/EthiopiaMap.vue
Implement country searching, details on click of map
=> [web] Build sidebar details for map

Track Sym Mobile App/src/localization/localization.js, Track Sym Mobile App/src/navigation/appNavigation.js, Track Sym Mobile App/src/pages/news/news.js, Track Sym Mobile App/src/pages/public-data-page/CustomText.js, Track Sym Mobile App/src/pages/references/index.js, Track Sym Mobile App/src/pages/settings/settings.js, Track Sym Mobile App/src/pages/symptom-page/UserSymptomPage.js
Unused imports on some pages are removed
=> [mobile] reference added and import optimized

Hack/Backend/routes/MessageRoutes.js, Hack/Backend/test/MessagesControllerTest.js
Temporarily disable the endpoints until we come up with better solutions to manage the feedbacks
=> [api] cleanup message

Track Sym Mobile App/src/navigation/appNavigation.js, Track Sym Mobile App/src/pages/symptom-history/index.js
Drawer footer have been updated.
=> Feysel.symptom history color

covid-19-app-web/src/views-admin/symptoms/SymptomDetails.vue, covid-19-app-web/src/views-admin/symptoms/Symptoms.vue, covid-19-app-web/src/views-admin/symptoms/dummy.js
[web] Initial symptom detail layout
[web] Vertical divider in symptom page filter
Eslint error fixed
[web] Removed unused method
=> [web] Initial admin symptom page layout

covid-19-app-web/src/components/core/AppBar.vue, covid-19-app-web/src/router/admin.js, covid-19-app-web/src/views-admin/auth/ChangePassword.vue, covid-19-app-web/src/views-admin/auth/CreateAccount.vue, covid-19-app-web/src/views-admin/auth/ForgotPassword.vue, covid-19-app-web/src/views-admin/auth/InviteAdmin.vue, covid-19-app-web/src/views-admin/symptoms/SymptomFilter.vue, covid-19-app-web/src/views/Auth/Login.vue, covid-19-app-web/src/views/Auth/Register.vue, covid-19-app-web/src/views/Profile/Profile.vue
=> Revert "[web] Change the color of navbar"

covid-19-app-web/src/store/cases.js, covid-19-app-web/src/store/symptoms.js, covid-19-app-web/src/views-admin/cases/CaseFilter.vue, covid-19-app-web/src/views-admin/cases/Cases.vue, covid-19-app-web/src/views-admin/symptoms/SymptomFilter.vue, covid-19-app-web/src/views-admin/symptoms/Symptoms.vue
Added username filter for cases and risk filter for symptoms
=> Beimnet.admin cases view

Backend/controllers/CaseInvestigationController.js, Backend/routes/CaseInvestigationRoutes.js
Get patients with status(New, Recovered . . . ) and the assigned healthcare worker
=> [api] added filters to get patients

covid-19-app-web/package-lock.json, covid-19-app-web/src/store/admin/dashboard.js, covid-19-app-web/src/store/loaders.js, covid-19-app-web/src/views-admin/dashboard/Dashboard.vue, covid-19-app-web/src/views-admin/dashboard/TotalStatistics.vue
[web] Dashboard date filter integrated
=> [web] Dashboard trend-graph integrated
